// What a piece is a picture of.
//
// The preview packs one block per shipped request, and slice 4B gives each
// block a painted tile. A tile needs a kind, and the sim does not have one:
// `BuiltPiece` is `{ id, size }` and stays that way, because the play-throughs
// are byte-identical runs of the sim and a field added there would move them.
// So the kind is derived here, in the shell, from the snippet the request just
// shipped — a pure function of what the corpus already says.
//
// Two steps, in this order:
//
//  1. The snippet's own topics, first match wins. A snippet tagged `for-loop`
//     draws a ring; one tagged `window-function` draws a grid of cells. The
//     table below is the whole of it, and the order a snippet lists its topics
//     in is the order they are tried, so the mapping is stable for a run and
//     stable between runs.
//  2. Failing that, a hash of the snippet's id, modulo eight. The corpus has
//     498 distinct topics over 249 snippets and a table that named all of them
//     would be a second corpus to maintain; the hash covers the tail and is
//     just as deterministic.
//
// Nothing here reads the clock, the seed or the run, so the same snippet is
// the same picture in every run on every machine.

import { hashString, type Snippet } from '@mcp-arcade-cabinets/vibe-typer';

/** The eight tiles a stack has, in the order every contact sheet draws them. */
export const PIECE_KINDS = [
  'function',
  'table',
  'button',
  'route',
  'loop',
  'file',
  'message',
  'chart',
] as const;

export type PieceKind = (typeof PIECE_KINDS)[number];

/**
 * Topic to picture. Curated, not exhaustive: a topic that is plainly one of
 * the eight things is named here, and everything else takes the hash. The
 * point is that a player who ships a loop sees a ring often enough to feel
 * the connection, not that every topic in the corpus has an opinion.
 *
 * `integration` is deliberately absent. Every snippet in that stack carries
 * it, so mapping it would draw the same tile for the whole stack; the ids
 * (`int-<server>-<tool>-<band>`) hash apart nicely and give the wires stack
 * the same variety the others get.
 *
 * The table is written as a literal and read through a Map. The corpus really
 * does carry topics called `constructor` and `toString`, and an index into a
 * plain object would answer those two from `Object.prototype` — every snippet
 * whose topics missed the table would come back with a function where a kind
 * should be. A Map has no prototype to fall through to.
 */
const TOPIC_TABLE: Record<string, PieceKind> = {
  // ——— a small machine with an input and an output ———
  functions: 'function',
  function: 'function',
  methods: 'function',
  method: 'function',
  lambda: 'function',
  'arrow-function': 'function',
  closures: 'function',
  'higher-order-functions': 'function',
  recursion: 'function',
  'recursive descent': 'function',
  constructors: 'function',
  decorators: 'function',
  'decorator-pattern': 'function',
  generics: 'function',
  'bounded-types': 'function',
  'type-erasure': 'function',
  wildcards: 'function',
  callbacks: 'function',
  functional: 'function',
  'functional-interface': 'function',
  predicate: 'function',
  delegates: 'function',
  'extension-methods': 'function',
  'method-reference': 'function',
  'abstract-method': 'function',
  'abstract methods': 'function',
  'default-method': 'function',
  'default-methods': 'function',
  'default arguments': 'function',
  'default-parameters': 'function',
  override: 'function',
  'private-methods': 'function',
  params: 'function',
  arguments: 'function',
  'argument-parsing': 'function',
  'return-value': 'function',
  return: 'function',
  memoization: 'function',
  functools: 'function',
  plpgsql: 'function',
  'returns-table': 'function',
  'utility-class': 'function',
  'factory-pattern': 'function',
  'builder-pattern': 'function',
  'builder pattern': 'function',
  'visitor-pattern': 'function',
  'fluent-api': 'function',
  partial: 'function',

  // ——— a grid of blank cells ———
  cte: 'table',
  'recursive-cte': 'table',
  'multi-cte': 'table',
  'writeable-cte': 'table',
  select: 'table',
  'basic-query': 'table',
  where: 'table',
  'where-in': 'table',
  'in-list': 'table',
  join: 'table',
  'inner-join': 'table',
  'left-join': 'table',
  'self-join': 'table',
  'cross-join': 'table',
  'lateral-join': 'table',
  'group-by': 'table',
  'order-by': 'table',
  having: 'table',
  groupby: 'table',
  grouping: 'table',
  'grouping-sets': 'table',
  groupingBy: 'table',
  subquery: 'table',
  'correlated-subquery': 'table',
  'nested-in': 'table',
  exists: 'table',
  'not-exists': 'table',
  insert: 'table',
  'insert-select': 'table',
  'multi-row': 'table',
  update: 'table',
  'update-from': 'table',
  delete: 'table',
  upsert: 'table',
  'on-conflict': 'table',
  returning: 'table',
  dml: 'table',
  ddl: 'table',
  'create-table': 'table',
  'materialized-view': 'table',
  index: 'table',
  indexing: 'table',
  indexer: 'table',
  trigger: 'table',
  'window-function': 'table',
  'partition-by': 'table',
  arrays: 'table',
  array: 'table',
  'multidimensional-arrays': 'table',
  matrix: 'table',
  'matrix-multiplication': 'table',
  'linear-algebra': 'table',
  'gaussian-elimination': 'table',
  sparse: 'table',
  grid: 'table',
  dictionary: 'table',
  dictionaries: 'table',
  dict: 'table',
  map: 'table',
  hashmap: 'table',
  'hash map': 'table',
  'associative-arrays': 'table',
  'entry-set': 'table',
  entries: 'table',
  collections: 'table',
  list: 'table',
  lists: 'table',
  set: 'table',
  tuples: 'table',
  records: 'table',
  record: 'table',
  dataclasses: 'table',
  schema: 'table',
  'data structures': 'table',
  'linked list': 'table',
  'binary search tree': 'table',
  unnest: 'table',
  jsonb: 'table',
  'json-agg': 'table',
  'json-build-object': 'table',
  registry: 'table',
  'registry pattern': 'table',
  'repository-pattern': 'table',
  repository: 'table',
  cache: 'table',
  eviction: 'table',
  'priority-queue': 'table',
  'priority queue': 'table',
  heapq: 'table',
  'bill-of-materials': 'table',

  // ——— a raised cap you press ———
  events: 'button',
  'event emitter': 'button',
  'observer-pattern': 'button',
  'observer pattern': 'button',
  reactive: 'button',
  actions: 'button',
  'state-management': 'button',
  'state management': 'button',
  'state-machine': 'button',
  'lifecycle-hooks': 'button',
  'plugin-system': 'button',
  interactive: 'button',
  commands: 'button',
  signals: 'button',
  guards: 'button',
  'command-check': 'button',
  'command-substitution': 'button',
  trap: 'button',
  eval: 'button',
  'process-management': 'button',
  supervisor: 'button',
  scheduler: 'button',
  scheduling: 'button',
  'cancellation-token': 'button',
  cancellation: 'button',
  'computed-property': 'button',
  'computed-properties': 'button',
  'shorthand-properties': 'button',
  properties: 'button',
  getter: 'button',
  getters: 'button',

  // ——— a road with a bend ———
  routing: 'route',
  http: 'route',
  'http-client': 'route',
  httpclient: 'route',
  HttpClient: 'route',
  aiohttp: 'route',
  fetch: 'route',
  middleware: 'route',
  pipeline: 'route',
  'pipeline pattern': 'route',
  pipes: 'route',
  pipefail: 'route',
  redirection: 'route',
  'process-substitution': 'route',
  graph: 'route',
  'adjacency-list': 'route',
  bfs: 'route',
  pathfinding: 'route',
  'shortest-path': 'route',
  'tree traversal': 'route',
  'tree-algorithms': 'route',
  backtracking: 'route',
  branching: 'route',
  'chain of responsibility': 'route',
  chaining: 'route',
  'method-chaining': 'route',
  'dependency-injection': 'route',
  'dependency-resolution': 'route',
  proxy: 'route',
  delegation: 'route',
  ssh: 'route',
  scp: 'route',
  'tcp-check': 'route',
  deployment: 'route',
  'virtual-dom': 'route',
  diffing: 'route',
  selectors: 'route',
  'dependency-tracking': 'route',
  hierarchy: 'route',
  'cycle-detection': 'route',
  'divide-and-conquer': 'route',
  'dynamic-programming': 'route',
  knapsack: 'route',
  optimization: 'route',
  'funnel-analysis': 'route',

  // ——— a closed ring ———
  'for-loop': 'loop',
  'for loop': 'loop',
  'while-loop': 'loop',
  'while loop': 'loop',
  'nested-loops': 'loop',
  loop: 'loop',
  loops: 'loop',
  iteration: 'loop',
  'for-each': 'loop',
  foreach: 'loop',
  'for-of': 'loop',
  'for-await-of': 'loop',
  'enhanced-for': 'loop',
  iterator: 'loop',
  iterables: 'loop',
  iterable: 'loop',
  generator: 'loop',
  generators: 'loop',
  'async-generator': 'loop',
  'async-enumerable': 'loop',
  yield: 'loop',
  range: 'loop',
  'generate-series': 'loop',
  enumerate: 'loop',
  zip: 'loop',
  'list comprehension': 'loop',
  'list-comprehension': 'loop',
  reduce: 'loop',
  accumulator: 'loop',
  filter: 'loop',
  filtering: 'loop',
  'filter-clause': 'loop',
  collect: 'loop',
  collector: 'loop',
  collectors: 'loop',
  sorting: 'loop',
  'merge-sort': 'loop',
  comparator: 'loop',
  comparable: 'loop',
  retry: 'loop',
  'retry pattern': 'loop',
  'exponential backoff': 'loop',
  backpressure: 'loop',
  pagination: 'loop',
  streams: 'loop',
  concurrency: 'loop',
  parallelism: 'loop',
  threading: 'loop',
  'thread pool': 'loop',
  'read-write-lock': 'loop',
  semaphore: 'loop',
  async: 'loop',
  'async-await': 'loop',
  await: 'loop',
  asyncio: 'loop',
  promises: 'loop',
  promise: 'loop',
  then: 'loop',
  futures: 'loop',
  'completable-future': 'loop',
  'task-run': 'loop',
  Task: 'loop',
  timers: 'loop',
  wait: 'loop',
  'background-jobs': 'loop',
  'worker-pattern': 'loop',
  shift: 'loop',
  decrement: 'loop',
  'prime numbers': 'loop',
  'forward-pass': 'loop',
  'neural-network': 'loop',
  convolution: 'loop',
  sobel: 'loop',
  'image-processing': 'loop',
  'edge-detection': 'loop',

  // ——— a page with a folded corner ———
  'file-io': 'file',
  'file I/O': 'file',
  io: 'file',
  'os module': 'file',
  read: 'file',
  find: 'file',
  ls: 'file',
  mkdir: 'file',
  rmdir: 'file',
  cd: 'file',
  pwd: 'file',
  stat: 'file',
  du: 'file',
  gzip: 'file',
  chmod: 'file',
  backup: 'file',
  'log-rotation': 'file',
  csv: 'file',
  json: 'file',
  serialization: 'file',
  parsing: 'file',
  parser: 'file',
  lexer: 'file',
  tokenizer: 'file',
  ast: 'file',
  heredoc: 'file',
  sed: 'file',
  awk: 'file',
  grep: 'file',
  regex: 'file',
  BASH_REMATCH: 'file',
  'field-parsing': 'file',
  'config-parsing': 'file',
  configuration: 'file',
  source: 'file',
  export: 'file',
  environment: 'file',
  'build-system': 'file',
  git: 'file',
  'try-with-resources': 'file',
  'auto-close': 'file',
  'with statement': 'file',
  'context managers': 'file',
  'deep copy': 'file',
  postgresql: 'file',
  annotations: 'file',
  'custom-annotation': 'file',
  reflection: 'file',
  inspect: 'file',
  metaprogramming: 'file',
  metaclasses: 'file',
  descriptors: 'file',
  'module-pattern': 'file',

  // ——— an empty speech bubble ———
  echo: 'message',
  print: 'message',
  println: 'message',
  printf: 'message',
  console: 'message',
  output: 'message',
  strings: 'message',
  string: 'message',
  'string-format': 'message',
  'string-building': 'message',
  'string-interpolation': 'message',
  StringBuilder: 'message',
  interpolation: 'message',
  concatenation: 'message',
  formatting: 'message',
  'f-string': 'message',
  'f-strings': 'message',
  'template-literals': 'message',
  quoting: 'message',
  IFS: 'message',
  'parameter-expansion': 'message',
  'indirect-expansion': 'message',
  'dunder methods': 'message',
  encapsulation: 'message',
  symbol: 'message',
  'error-handling': 'message',
  'error handling': 'message',
  'exception-handling': 'message',
  'exception handling': 'message',
  'try-catch': 'message',
  'try-except': 'message',
  exception: 'message',
  exceptions: 'message',
  catch: 'message',
  rollback: 'message',
  validation: 'message',
  assertions: 'message',
  test: 'message',
  'test-framework': 'message',
  tap: 'message',
  contracts: 'message',
  'null-safety': 'message',
  'null-handling': 'message',
  nullable: 'message',
  'nullish-coalescing': 'message',
  coalesce: 'message',
  Optional: 'message',

  // ——— bars of different heights ———
  statistics: 'chart',
  aggregate: 'chart',
  aggregation: 'chart',
  avg: 'chart',
  count: 'chart',
  rank: 'chart',
  ntile: 'chart',
  'percent-rank': 'chart',
  lag: 'chart',
  greatest: 'chart',
  pivot: 'chart',
  'log-analysis': 'chart',
  'log-stats': 'chart',
  monitoring: 'chart',
  report: 'chart',
  timing: 'chart',
  wc: 'chart',
  uniq: 'chart',
  sort: 'chart',
  length: 'chart',
  arithmetic: 'chart',
  'integer division': 'chart',
  modulo: 'chart',
  clamping: 'chart',
  comparison: 'chart',
  'loss-function': 'chart',
  'leaky-relu': 'chart',
  normalization: 'chart',
  'cost-rollup': 'chart',
  interval: 'chart',
  extract: 'chart',
  date: 'chart',
  classification: 'chart',
  audit: 'chart',
  values: 'chart',
};

export const TOPIC_KINDS: ReadonlyMap<string, PieceKind> = new Map<string, PieceKind>([
  ...Object.entries(TOPIC_TABLE),
  // Two topics the corpus really carries whose names are already members of
  // every object. They are entries here rather than lines in the literal
  // above because a property called `constructor` in an object type is the
  // one `Object.prototype` declares, and cannot be a piece kind as well.
  ['constructor', 'function'],
  ['toString', 'message'],
]);

/**
 * The tile a shipped snippet draws. Total: every snippet gets one of the
 * eight, and the same snippet always gets the same one.
 */
export function pieceKindOf(snippet: Pick<Snippet, 'id' | 'topics'>): PieceKind {
  for (const topic of snippet.topics) {
    const named = TOPIC_KINDS.get(topic);
    if (named) return named;
  }
  return PIECE_KINDS[hashString(snippet.id) % PIECE_KINDS.length]!;
}

/** True when the topics named the kind, rather than the id's hash. */
export function namedByTopic(snippet: Pick<Snippet, 'topics'>): boolean {
  return snippet.topics.some((topic) => TOPIC_KINDS.has(topic));
}
